// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmanyxiyymkycfxpwprx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtYW55eGl5eW1reWNmeHB3cHJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MjgzNTksImV4cCI6MjA3NDAwNDM1OX0.HdzMFqL212wgJXvnxo32qWjs9gwlGlcizbzelFNuXgQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});